### ISSUE TITLE
AERO-17

### ISSUE THREAD

**Issue by sephentos** [Ghioaga/AeroMinimal#1]
Hey,
I'm using an AERO 17 WB with Windows 11.
I'd wish to use this tool with my aero as well since I can't use that garbage buggy control center tool of gigabyte.
If you need some feedback or testing with an aero 17 user feel free to contact me :)

**Comment by Ghioaga** [comment]
Hello, it should work without issue as far as I know, but if you run into problems give me a message on reddit and I will help you and also debug it as well as for any questions you have feel free to get in touch with me there. The latest version is in the Releases, 1.0.0.7, and it should work on windows 11 as I tested it with u/gran_lexu. But feel free to get in touch with me over reddit. if you don't have reddit I'm also on Discord as Ghioaga#7431

**Comment by sephentos** [comment]
Hey! Thanks for the reply.
I'll get in contact with you soon, but I'm currently in a busy week. 

But I can share you the screenshot I get when starting your tool:
I don't think Windows 11 is the issue, it's just that aero 17 seems not to be supported. That's why I offered me as a tester :)

![image](https://user-images.githubusercontent.com/35430448/136364413-d6750397-8360-44ee-8589-cd2c45f48a9a.png)

**Comment by Ghioaga** [comment]
yeah i's a bug I don't get to find the source of, I will see to it next time I reinstall my PC and see if it happens as it's not every time and at every install.
Please try to reinstall AeroMinimal firstly. And if it doesn't work unzip the archive from the link and run the bat file as admin.

https://we.tl/t-WoRn0BqcCo

Thank you. This is my part not the AeroCtl dev :D

**Comment by Ghioaga** [comment]
Before you try the link if it still doesn't work try the latest version I made 1.0.0.8 please.
