### ISSUE TITLE
project still alive?

### ISSUE THREAD

**Issue by TwoXTwentyOne** [Ghioaga/AeroMinimal#2]
Is this project still active?

**Comment by Ghioaga** [comment]
Hello, yes it's still active, it's just that I've been on my actual job that is merchant navy officer and I hadn't have time or internet to work more on it, if you want to help the development I would be more than happy.

**Comment by TwoXTwentyOne** [comment]
Oh just checking :)

Would love to help, but network security is my domain and not so much coding unfortunately.

Thank you for your service sir, keep safe!

**Comment by TwoXTwentyOne** [comment]
If by chance you could chime into this thread for the author of AeroCtl, it would be cool, whenever you got time that is... :)

https://gitlab.com/wtwrp/aeroctl/-/issues/36

I tried tagging you on there, but I'm not sure what your username is.

**Comment by Ghioaga** [comment]
Well yes actually try and use the appropriate zip file from the latest release, when I'll get home I'll try and update the install with this thing as well. use the instructions from the latest release page.
