### ISSUE TITLE
Cannot run app. Needs .net, which I already have installed

### ISSUE THREAD

**Issue by GoTeamScotch** [Ghioaga/AeroMinimal#3]
I have been using AeroCtl on my 2022 Aero 17 HDR XD and it's been working great. I found AeroMinimal and figured it would be a slightly better way of using AeroCtl, since it also included Fusion. I installed AeroMinimal this morning and I can't seem to get it to work. When launching it from the Start Menu, it gives an error: "To run this application, you must install .net" and it gives me the option to download .net (clicking Yes does nothing).

![image](https://user-images.githubusercontent.com/11036843/219067750-c9b6cfdc-f55b-47c4-a263-e6622e4c6fc1.png)

But I already have .net installed on my PC. And it doesn't say which version of .net. I have the latest version, plus older ones I'm sure.

When I restart my PC, I can see AeroCtl running in taskmanager, then after a while it goes away like the app closes itself. It must be crashing silently. I never see the AeroCtl app itself, or see its icon in the system tray.

And again, AeroCtl was working on my laptop just fine. The copy bundled in with AeroMinimal does not. Now, when going to launch the other copy of AeroCtl I have (the one that I had been using for some time), that copy now no longer works. 

![image](https://user-images.githubusercontent.com/11036843/219067858-e7c11336-829c-45dc-84b1-44bc80f70377.png)

Any suggestions? What version of .net does this app expect?

I should mention that I already had Gigabyte's software installed. Is that a problem? Do I need to remove Gigabyte's software before using AeroMinimal? I have their software set to not auto-start. When I launch it, it doesn't seem to be able to control my fans anymore, which is odd.

Thanks!

**Comment by Ghioaga** [comment]
Hello, this is the version of NET that the app needs: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.9-windows-x64-installer

And about that error try using the fix from the releases downloads the one named ControlCenter.Laptop.zip

It's weird that you have Control center installed and it gives you this error. Also if you uninstall the Gigabyte stuff I think you will need to run the Fix again.
